"""Set up and maintain a job-search data folder. Stdlib only (runs before the venv exists).

  setup.py init --home DIR --country IN [--cities "delhi ncr,bengaluru"] [--remote-bias strong|some|none]
                [--timezone Asia/Kolkata] [--forbidden-shift 00:00-06:00] [--salary-floor N | --salary-floor-lpa N]
                [--max-yoe 5] [--tracker csv|gsheets] [--indeed PREFIX] [--no-env] [--preset free]
      Create the folder (config.yaml, preferences, CLAUDE.md, .gitignore, data/ …), the Python env and ./js.
  setup.py link [--home DIR] [--dev]
      Refresh ./js and the rendered agents (.claude/agents/) for this plugin version, and register the folder
      for the MCP server. Idempotent; run by the skill
      at the start of every run. --dev also symlinks .claude/skills/job-search to this repo (no plugin install).
  setup.py env [--home DIR]      create/refresh .venv (uses uv when available) and install requirements
  setup.py doctor [--home DIR]   check python, deps, config, pack, profiles, tracker, keys, agents
  setup.py desktop-config [--home DIR] [--write]
      Print the Claude Desktop mcpServers entry for this folder; --write merges it into Desktop's config file
      (keeping a .bak copy).

Nothing here creates accounts or handles credentials; keys are placed in .secrets/ by the user.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

import homes

SCRIPTS = Path(__file__).resolve().parent
SKILL = SCRIPTS.parent
PLUGIN = SKILL.parents[1]
TEMPLATES = PLUGIN / "templates"
MIN_PY = (3, 10)
# `init --preset`: cheaper settings for plans with small message limits (scored in chat, a few jobs at a time)
PRESETS = {"free": {"shortlist_size": 6, "scorer_batch_size": 3, "max_age_days": 10}}
GENERATED = "<!-- generated by job-search setup.py link from templates/agents — edit the template, not this file -->"


def _home(a) -> Path:
    h = Path(a.home or os.environ.get("JOB_SEARCH_HOME") or Path.cwd()).expanduser().resolve()
    return h


def _render(text: str, values: dict) -> str:
    return re.sub(r"\{\{(\w+)\}\}", lambda m: str(values.get(m.group(1), m.group(0))), text)


def _set_scalar(text: str, key: str, value) -> str:
    """Replace `key: value` (first top-level line) keeping its comment; setup runs before PyYAML exists."""
    new, n = re.subn(rf"(?m)^({re.escape(key)}:[ \t]*)[^#\n]*?([ \t]*(#.*)?)$", rf"\g<1>{value}\g<2>", text, count=1)
    if n != 1:
        raise KeyError(key)
    return new


def _write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _read_yaml_scalar(text: str, key: str):
    """Tiny reader for `key: value` lines (setup must work before PyYAML is installed)."""
    m = re.search(rf"(?m)(?:^\s*|[{{,]\s*){re.escape(key)}:[ \t]*([^#\n,}}]*)", text)  # block or inline mapping
    if not m:
        return None
    v = m.group(1).strip().strip('"').strip("'")
    return {"true": True, "false": False, "null": None, "": None}.get(v.lower(), v)


# ---------- link: ./js wrapper + rendered agents ----------

JS = """#!/bin/sh
# job-search CLI for this data folder (generated by setup.py link; re-run it after plugin updates).
#   ./js <plan|feeds|filter|decide|shortlist|publish|fetch-url|track|status|context> [...]
#   ./js tracker <check|init|flush>   ./js discover <...>   ./js setup <link|doctor|env>
HOME_DIR="$(cd "$(dirname "$0")" && pwd)"
S="{scripts}"
PY="$HOME_DIR/.venv/bin/python"
[ -x "$PY" ] || PY=python3
export JOB_SEARCH_HOME="$HOME_DIR"
cd "$HOME_DIR" || exit 1
case "$1" in
  tracker|sheets) shift; exec "$PY" "$S/tracker.py" "$@";;
  discover) shift; exec "$PY" "$S/discover.py" "$@";;
  setup) shift; exec python3 "$S/setup.py" "$@" --home "$HOME_DIR";;
esac
exec "$PY" "$S/jobsearch.py" "$@"
"""


OWN_MCP = "mcp__plugin_trawlnet"  # this plugin's own MCP server also has a search_jobs tool: never the Indeed connector


def _indeed_prefix(text: str):
    prefix = _read_yaml_scalar(text, "indeed_tool_prefix")
    return None if str(prefix or "").strip().startswith(OWN_MCP) else prefix


def _agent_values(home: Path) -> dict:
    cfg = (home / "config.yaml").read_text(encoding="utf-8") if (home / "config.yaml").exists() else ""
    indeed = _indeed_prefix(cfg)
    indeed_on = _read_yaml_scalar(cfg, "indeed")
    use = bool(indeed) and indeed_on is not False
    refs = SKILL / "references"
    return {
        "FETCHER_MODEL": _read_yaml_scalar(cfg, "fetcher_model") or "haiku",
        "SCORER_MODEL": _read_yaml_scalar(cfg, "scorer_model") or "sonnet",
        "RESEARCHER_MODEL": _read_yaml_scalar(cfg, "researcher_model") or "haiku",
        "INDEED_SEARCH_TOOL": f", {indeed}__search_jobs" if use else "",
        "INDEED_DETAILS_TOOL": f", {indeed}__get_job_details" if use else "",
        "INDEED_NOTE": "" if use else "The Indeed connector is not configured: skip Indeed steps; `indeed:` JD ids "
                                      "cannot occur.",
        "SCORING_RUBRIC": (refs / "scoring-rubric.md").read_text(encoding="utf-8").strip(),
        "TAILORING_RULES": (refs / "tailoring-rules.md").read_text(encoding="utf-8").strip(),
        "GENERATED": GENERATED,
    }


def link(home: Path, dev: bool = False) -> list:
    changed = []
    js = home / "js"
    if _write_if_changed(js, JS.replace("{scripts}", str(SCRIPTS))):
        changed.append("js")
    js.chmod(0o755)
    # Exactly the folder given, and only if it is a data folder.
    found = homes.nearest(home, walk=False)
    try:
        if found and homes.register(found):
            changed.append(f"registered {found} for the MCP server (restart Claude Code or Claude Desktop to use it)")
    except (OSError, ValueError) as e:  # e.g. ~/.config not writable: the run itself does not need it
        print(f"WARN could not register the folder for the MCP server: {e}", file=sys.stderr)
    vals = _agent_values(home)
    for t in sorted((TEMPLATES / "agents").glob("*.md")):
        if _write_if_changed(home / ".claude" / "agents" / t.name, _render(t.read_text(encoding="utf-8"), vals)):
            changed.append(f".claude/agents/{t.name}")
    if dev:
        dst = home / ".claude" / "skills" / "job-search"
        if dst.is_symlink() and dst.resolve() == SKILL:
            pass
        elif dst.exists() and not dst.is_symlink():
            sys.exit(f"{dst} is a real folder; move it away before linking the dev plugin")
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            if dst.is_symlink():
                dst.unlink()
            dst.symlink_to(SKILL, target_is_directory=True)
            changed.append(".claude/skills/job-search -> plugin (dev)")
    return changed


# ---------- env ----------

def _need_python() -> None:
    """Exit unless this Python can build the venv; `init` asks first, so a too-old python3 leaves no half-made folder."""
    if sys.version_info < MIN_PY:
        sys.exit(f"Python >= {'.'.join(map(str, MIN_PY))} needed for the env (this is {sys.version.split()[0]}); "
                 "install a newer python3 or uv, and run this command with it (e.g. python3.12 setup.py ...)")


def env(home: Path) -> str:
    venv = home / ".venv"
    req = PLUGIN / "requirements.txt"
    uv = shutil.which("uv")
    if uv:
        if not venv.exists():
            subprocess.run([uv, "venv", "--python", ">=3.10", str(venv)], check=True, capture_output=True)
        subprocess.run([uv, "pip", "install", "-q", "--python", str(venv / "bin" / "python"), "-r", str(req)],
                       check=True)
        return "env: uv venv ready"
    _need_python()
    if not venv.exists():
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
    subprocess.run([str(venv / "bin" / "python"), "-m", "pip", "install", "-q", "-r", str(req)], check=True)
    return "env: venv ready"


# ---------- init ----------

def init(a) -> None:
    if (a.indeed or "").strip().startswith(OWN_MCP):
        sys.exit(f"--indeed {a.indeed} is trawlnet's own MCP server, not the Indeed connector; "
                 "pass the claude.ai Indeed connector's prefix or omit --indeed")
    if a.preset and a.indeed:
        sys.exit(f"--preset {a.preset} does not use the Indeed connector (it needs Claude Code); drop --indeed")
    home = _home(a)
    if (home / "config.yaml").exists():
        sys.exit(f"{home}/config.yaml exists; edit it instead (or choose another --home)")
    if not a.no_env and not shutil.which("uv"):
        _need_python()
    pack = PLUGIN / "packs" / f"{a.country.lower()}.yaml"
    if not pack.exists():
        sys.exit(f"no pack for {a.country}; available: {', '.join(p.stem.upper() for p in (PLUGIN / 'packs').glob('*.yaml'))}")
    ptxt = pack.read_text(encoding="utf-8")
    for d in ("data/profiles", "data/resumes", "data/runs", "data/digests", "data/tailoring", "data/seeds", ".secrets"):
        (home / d).mkdir(parents=True, exist_ok=True)
    (home / ".secrets").chmod(0o700)
    cities = [c.strip().lower() for c in (a.cities or "").split(",") if c.strip()]
    catalog = {}
    block = re.search(r"(?ms)^cities:\n(.*?)(?=^\S)", ptxt)
    for line in (block.group(1) if block else "").splitlines():
        m = re.match(r"\s+([^:#]+):\s*\[(.*)\]", line)
        if m:
            catalog[m.group(1).strip()] = m.group(2)
    unknown = [c for c in cities if c not in catalog]
    if unknown:
        sys.exit(f"unknown cities {unknown}; the {a.country} pack has: {', '.join(catalog)}")
    city_yaml = "\n".join(f"  {c}: [{catalog[c]}]" for c in cities) or "  {}"
    tz = a.timezone or _read_yaml_scalar(ptxt, "timezone_default") or "UTC"
    currency = _read_yaml_scalar(ptxt, "currency")
    vals = {
        "COUNTRY": a.country.upper(), "CITIES": city_yaml, "TRACKER": a.tracker,
        "INDEED_PREFIX": a.indeed or "", "INDEED_ON": "true" if a.indeed else "false",
        "SEARCH_LOCATIONS": "\n".join(["  - remote"] + [f"  - {c.title()}" for c in cities]),
        "ADZUNA_LOCATIONS": ", ".join(c.title() for c in cities),
    }
    config = _render((TEMPLATES / "config.yaml").read_text(encoding="utf-8"), vals)
    for key, value in PRESETS.get(a.preset, {}).items():
        config = _set_scalar(config, key, value)
    (home / "config.yaml").write_text(config, encoding="utf-8")
    g = lambda x: f"{x:g}"  # noqa: E731  (26.0 -> 26)
    floor = (f"min_lpa: {g(a.salary_floor_lpa)}" if a.salary_floor_lpa else
             f"min_annual: {g(a.salary_floor)}" if a.salary_floor else "min_annual: null")
    prefs = (TEMPLATES / "preferences.yaml").read_text(encoding="utf-8")
    (home / "data/profiles/preferences.yaml").write_text(_render(prefs, {
        "SALARY_FLOOR": floor, "CURRENCY": currency, "MAX_YOE": g(a.max_yoe) if a.max_yoe is not None else "null",
        "REMOTE_BIAS": a.remote_bias, "TIMEZONE": tz, "FORBIDDEN_SHIFT": a.forbidden_shift or "",
    }), encoding="utf-8")
    (home / "CLAUDE.md").write_text(_render((TEMPLATES / "CLAUDE.md.tmpl").read_text(encoding="utf-8"), {
        "HOME": str(home), "COUNTRY": a.country.upper(), "CITIES": ", ".join(cities) or "none (remote only)",
        "REMOTE_BIAS": a.remote_bias, "TIMEZONE": tz, "FORBIDDEN_SHIFT": a.forbidden_shift or "none",
        "SALARY": floor.replace("min_lpa: ", "").replace("min_annual: ", "") + f" {currency}"
                  + (" LPA" if a.salary_floor_lpa else " / year"),
        "MAX_YOE": g(a.max_yoe) if a.max_yoe is not None else "no limit", "TRACKER": a.tracker,
    }), encoding="utf-8")
    shutil.copy(TEMPLATES / "gitignore", home / ".gitignore")
    print(f"data folder: {home}")
    if not a.no_env:
        print(env(home))
    print("linked:", ", ".join(link(home)) or "nothing to change")
    print("next: add a profile per resume (profile add), then `./js setup doctor`")
    if a.preset:
        print(f"preset {a.preset}: shortlist and batch sizes are small; "
              f"connect Claude Desktop with `python3 {shlex.quote(str(SCRIPTS / 'setup.py'))} desktop-config "
              f"--home {shlex.quote(str(home))}`")


# ---------- desktop-config ----------

def desktop_config_path() -> Path:
    """Where Claude Desktop keeps claude_desktop_config.json on this OS."""
    if sys.platform == "darwin":
        return Path.home() / "Library/Application Support/Claude/claude_desktop_config.json"
    if sys.platform == "win32":
        return Path(os.environ.get("APPDATA") or Path.home() / "AppData/Roaming") / "Claude/claude_desktop_config.json"
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config") / "Claude/claude_desktop_config.json"


def desktop_entry(home: Path) -> dict:
    """The mcpServers entry that starts this server on `home` (absolute paths: Desktop has no shell PATH or cwd)."""
    py = next((p for p in (home / ".venv" / "bin" / "python", home / ".venv" / "Scripts" / "python.exe")
               if p.exists()), Path(sys.executable))
    return {"command": str(py),
            "args": [str(SCRIPTS / "mcp_server.py")], "env": {"JOB_SEARCH_HOME": str(home)}}


def desktop_note(home: Path) -> str:
    """A warning for stderr (never the pasteable JSON) when the folder is not registered for the action tools."""
    if homes.is_registered(home):
        return ""
    return (f"note: {home} is not registered yet; run `python3 {shlex.quote(str(SCRIPTS / 'setup.py'))} link --home "
            f"{shlex.quote(str(home))}` or query_tracker, fetch_job_description and track_job will refuse")


def desktop_config(home: Path, write: bool = False) -> str:
    if not (home / "config.yaml").exists():
        sys.exit(f"{home} is not a data folder (no config.yaml); run `setup.py init --home {home}` first")
    entry = {"mcpServers": {"trawlnet": desktop_entry(home)}}
    if not write:
        return json.dumps(entry, indent=2)
    path = desktop_config_path()
    hand = "re-run without --write to print the entry and paste it by hand"
    try:
        current = json.loads(path.read_text(encoding="utf-8-sig")) if path.exists() else {}
        servers = current.setdefault("mcpServers", {}) if isinstance(current, dict) else None
    except (ValueError, OSError) as e:
        sys.exit(f"cannot update {path} ({e}); fix it, or {hand}")
    if not isinstance(servers, dict):
        sys.exit(f"{path} is not a Claude Desktop config (mcpServers must be an object); {hand}")
    servers["trawlnet"] = entry["mcpServers"]["trawlnet"]
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists():
            shutil.copy(path, path.with_name(path.name + ".bak"))
        path.write_text(json.dumps(current, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    except OSError as e:
        sys.exit(f"cannot write {path} ({e}); {hand}")
    return f"added trawlnet to {path} (previous file kept as {path.name}.bak); restart Claude Desktop"


# ---------- doctor ----------

SEED_STALE_DAYS = 180      # a seed list older than this is due for a refresh
DEAD_RATE_WARN = 0.15      # share of a seed's boards dead (gone_days >= DEAD_AFTER) that triggers a warning
DEAD_AFTER, DEAD_MIN = 3, 10  # DEAD_AFTER mirrors sources.DEAD_AFTER; DEAD_MIN = boards needed before judging


def seed_warnings(home: Path, today=None) -> list:
    """Staleness of the seeds behind data/companies.json: high dead-board rate, or an old list. Stdlib only."""
    today = today or dt.date.today()
    path = home / "data" / "companies.json"
    if not path.exists():
        return []
    mf = PLUGIN / "seeds" / "manifest.json"
    manifest = json.loads(mf.read_text(encoding="utf-8")) if mf.exists() else {}
    boards = {}
    for c in json.loads(path.read_text(encoding="utf-8")):
        if c.get("ats") != "custom" and c.get("seed"):
            boards.setdefault({"india": "in"}.get(c["seed"], c["seed"]), []).append(c)
    out = []
    for seed, cs in sorted(boards.items()):
        dead = sum(c.get("gone_days", 0) >= DEAD_AFTER for c in cs)
        if len(cs) >= DEAD_MIN and dead / len(cs) >= DEAD_RATE_WARN:
            out.append(f"seed '{seed}': {dead} of {len(cs)} boards are dead -> ./js discover refresh --seed {seed}")
        own = next((p for p in (home / "data/seeds" / f"{seed}{x}" for x in (".yaml", ".json")) if p.exists()), None)
        made = dt.date.fromtimestamp(own.stat().st_mtime).isoformat() if own else manifest.get(seed)
        if made and (today - dt.date.fromisoformat(made)).days > SEED_STALE_DAYS:
            out.append(f"seed '{seed}': list dates from {made} -> ./js discover refresh --seed {seed}, then ./js discover topup --seed {seed}")
    return out


def doctor(home: Path) -> None:
    ok = lambda b: "ok " if b else "!! "  # noqa: E731
    py = home / ".venv" / "bin" / "python"
    print(f"{ok(py.exists())}env {py if py.exists() else '(missing: ./js setup env)'}")
    if py.exists():
        r = subprocess.run([str(py), "-c", "import sys, yaml; print(sys.version.split()[0])"], capture_output=True,
                           text=True)
        print(f"{ok(r.returncode == 0)}python {r.stdout.strip() or r.stderr.strip()[-120:]}")
    cfg = home / "config.yaml"
    print(f"{ok(cfg.exists())}config.yaml")
    if not cfg.exists():
        return
    text = cfg.read_text(encoding="utf-8")
    cc = (_read_yaml_scalar(text, "country") or "?").lower()
    print(f"{ok((PLUGIN / 'packs' / f'{cc}.yaml').exists() or (home / 'packs' / f'{cc}.yaml').exists())}pack {cc}")
    profiles = [p.stem for p in (home / "data/profiles").glob("*.yaml") if p.stem not in ("master", "preferences")]
    print(f"{ok(bool(profiles))}profiles: {', '.join(profiles) or 'none (profile add <resume>)'}")
    print(f"{ok((home / 'data/profiles/preferences.yaml').exists())}preferences.yaml")
    for name, key, path in (("firecrawl", "firecrawl", ".secrets/firecrawl.key"),
                            ("adzuna", "adzuna", ".secrets/adzuna.json")):
        on = re.search(rf"(?m)^\s*{key}:\s*true" if key == "adzuna" else r"(?ms)^firecrawl:[^\n]*\n\s*enabled:\s*true", text)
        if on:
            print(f"{ok((home / path).exists())}{name} enabled, key {'present' if (home / path).exists() else 'MISSING at ' + path}")
    backend = _read_yaml_scalar(text, "backend") or "csv"
    if backend == "gsheets":
        k = _read_yaml_scalar(text, "service_account_key") or ".secrets/service-account.json"
        print(f"{ok((home / k).exists())}tracker gsheets, key {'present' if (home / k).exists() else 'MISSING'}")
    else:
        print(f"ok tracker {backend}")
    indeed = _indeed_prefix(text)
    print(f"{'ok ' if indeed else '-- '}indeed connector: {indeed or 'not configured (optional)'}")
    for w in seed_warnings(home):
        print(f"!! {w}")
    agents = [p.name for p in (home / ".claude/agents").glob("*.md")]
    print(f"{ok(len(agents) >= 3)}agents rendered: {', '.join(agents) or 'none (./js setup link)'}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["init", "link", "env", "doctor", "desktop-config"])
    ap.add_argument("--home")
    ap.add_argument("--dev", action="store_true")
    ap.add_argument("--country", default="IN")
    ap.add_argument("--cities")
    ap.add_argument("--remote-bias", default="strong", choices=["strong", "some", "none"])
    ap.add_argument("--timezone")
    ap.add_argument("--forbidden-shift")
    ap.add_argument("--salary-floor", type=float)
    ap.add_argument("--salary-floor-lpa", type=float)
    ap.add_argument("--max-yoe", type=float)
    ap.add_argument("--tracker", default="csv", choices=["csv", "gsheets"])
    ap.add_argument("--indeed", help="Indeed connector tool prefix, e.g. mcp__<server-id> (from the session's tool names)")
    ap.add_argument("--no-env", action="store_true")
    ap.add_argument("--preset", choices=sorted(PRESETS), help="cheaper settings for small message limits (free plans)")
    ap.add_argument("--write", action="store_true", help="desktop-config: merge the entry into Claude Desktop's config")
    a = ap.parse_args()
    if a.cmd == "init":
        init(a)
    elif a.cmd == "link":
        print("linked:", ", ".join(link(_home(a), a.dev)) or "up to date")
    elif a.cmd == "env":
        print(env(_home(a)))
    elif a.cmd == "desktop-config":
        home = _home(a)
        print(desktop_config(home, a.write))
        note = desktop_note(home)
        if note:
            print(note, file=sys.stderr)
    else:
        doctor(_home(a))


if __name__ == "__main__":
    main()
